name: CMake tests

on:
  push:
    branches: 
      - master
      - devel
  pull_request:
    branches:
      - master
      - devel

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [windows-2022]
    steps:
    - uses: actions/checkout@v4

    - name: Build dotnet support
      working-directory: ${{github.workspace}}/windows-setup
      run: dotnet build

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{github.workspace}}/External
        key: setup-deps-${{ matrix.os }}-${{ hashFiles('dependencies.json') }}
        restore-keys: |
          setup-deps-${{ matrix.os }}-${{ hashFiles('dependencies.json') }}

    - name: Install dependencies
      working-directory: ${{github.workspace}}/windows-setup
      run: |
        dotnet run installdeps ${{env.BUILD_TYPE}}
        $userPath = [System.Environment]::GetEnvironmentVariable("Path", "User")
        $userPath.Split(';') | Where-Object { $_ } | Add-Content $env:GITHUB_PATH

    - name: Install project VoronoiLatticeDistances
      working-directory: ${{github.workspace}}/windows-setup
      run: dotnet run install ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --build-config ${{env.BUILD_TYPE}} --build-target install
